language: node_js
# FOR SPEED
# cache:
#   directories:
#     - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist
script: npm start
